### ISSUE TITLE
long support not working in the Esper with Date-Time Methods

### ISSUE THREAD

**Issue by gourt** [Orange-OpenSource/fiware-cepheus#30]
When i send timestamp field  as long and try in the EPL query to do  `timestamp.get('minute') `  although in the Esper documentation it's said that it should work with long value (and it worked in the Esper4FastData) i get the following exception: 

`Date-time enumeration method 'get' requires either a Calendar, Date or long value as input or events of an event type that declares a timestamp property but received java.lang.Object `

when i did in the EPL  `typeof(timestamp)`  i got String  

i attached the log file so you will be able to check the exception 

[cep.txt](https://github.com/Orange-OpenSource/fiware-cepheus/files/49494/cep.txt)

**Comment by marcc-orange** [comment]
Can you tell what version you are using ? We just corrected support for attributes of type `long` on the `0.1.2` #28.

**Comment by gourt** [comment]
Sorry i forgot to mention it we are you using the latest  `0.1.2`

**Comment by marcc-orange** [comment]
If you configure the incoming event in the `in` section of the configuration to use type `long` for the `mesg.time` attribute, you should not have to cast to string then to long.
Maybe Esper does not support calling .get('hour') on a `Long` object but only on a `long` primitive type.

**Comment by gourt** [comment]
I did configure in the   `in `  that the time field will use long, but  still it looks like Esper get it as String 
cause this line  : `Long.valueOf(cast(mesg.time,string)).get('hour') `   works fine.
but this one:  `  cast(mesg.time,long).get('hour')`   returns null when i run the query

**Comment by marcc-orange** [comment]
Using `0.1.2`, I managed to convert some time values using `long` type.

# Configuration
```json
{
  "host":"http://localhost:8080",
  "in":[
    {
      "id":"Test1",
      "type":"Test",
      "attributes":[
        { "name":"time", "type":"long" }
      ]
    }
  ],
  "out":[
    {
      "id":"TestOut1",
      "type":"TestOut",
      "attributes":[
        { "name":"ahour", "type":"long" },
        { "name":"amin", "type":"long" },
        { "name":"aday", "type":"long" },
        { "name":"ayear", "type":"long" },
        { "name":"amonth", "type":"long" }
      ]
    }
  ],
  "statements":[
    "INSERT INTO TestOut SELECT 'TestOut1' as id, time.get('hour') as ahour, time.get('min') as amin, time.get('day') as aday, time.get('month') as amonth, time.get('year') as ayear FROM Test"
  ]
}
```
# UpdateContext payload
```json
{
  "contextElements": [
    {
      "type": "Test",
      "isPattern": "false",
      "id": "test1",
      "attributes": [
        {
          "name": "time",
          "type": "long",
          "value": "1435755440000"
        }
      ]
    }
  ],
  "updateAction": "APPEND"
}
```

# Output
```
2015-12-02 14:35:36.061  INFO 32387 --- [io-8080-exec-17] c.o.cepheus.cep.EsperEventProcessor      : EventIn: Event{type='Test', values={time=1435755440000, id=test1}}
2015-12-02 14:35:36.061  INFO 32387 --- [io-8080-exec-17] c.orange.cepheus.cep.EventSinkListener   : EventOut: TestOut / ayear:2015 / ahour:14 / amonth:6 / aday:1 / id:TestOut1 / amin:57 from insert into TestOut select "TestOut1" as id, time.get('hour') as ahour, time.get('min') as amin, time.get('day') as aday, time.get('month') as amonth, time.get('year') as ayear from Test
```
Note: the conversion operated by `get` is taking the current timezone in account  (UTC+2 here).

**Comment by marcc-orange** [comment]
@gourt Did my last answer helped you ? You can close this issue if long support is working for you.
