### ISSUE TITLE
Using Cepheus

### ISSUE THREAD

**Issue by abbasahmad** [Orange-OpenSource/fiware-cepheus#31]
Hello,

i was looking for Espr4FastData and i found this. Is it good for production env ? 
I will begin testing it soon this afternoon.

**Comment by marcc-orange** [comment]
Hi @abbasahmad !

Our target is production, yes. 
The project is quite new (first released in september 2015) but should work !
What are you going to test ?

If you're new to Fiware-Cepheus, the starting point is here: [user manual](http://fiware-cepheus.readthedocs.org/en/latest/).

Please keep us informed of any problem you encounter and we'd really appreciate any feedback.

**Comment by abbasahmad** [comment]
Hey,

I have been in Fiware since Friendly testing. i started using Espr4FastData long time ago. Now it has been outdated and renewed in Orange as Cepheus. 

I am doing a PhD in Future internet platforms Testing and that includes the Model Based Testing of Fiware Generic Enablers Implementations.
I have wrriten a white paper on Espr4fastData Case study : https://dl.dropboxusercontent.com/u/95118199/Case%20study%20-%20ESPR4FASTDATA_vFInale.pdf 

For now i Just want to get a hand on the Cepheus Enabler and see how it works in order to better test it.  I will keep in toutch but not sure if you would like to keep the communication here? You prefer Email or anything else let me know.

Abbas AHMAD
Easy Global Market

**Comment by marcc-orange** [comment]
Using the GitHub issues is fine with us, so that other users can benefit from our exchanges.
