### ISSUE TITLE
QueryContext sends empty restriction.

### ISSUE THREAD

**Issue by dkgof** [Orange-OpenSource/fiware-cepheus#4]
Hi,

When i use a QueryContext to send a query to http://orion.lab.fiware.org:1026 without defining any restrictions, i get this reply from the server:

```
<queryContextResponse>
  <errorCode>
    <code>400</code>
    <reasonPhrase>Bad Request</reasonPhrase>
    <details>empty restriction</details>
  </errorCode>
</queryContextResponse>
```

The query sent to the server is:
```
<queryContextRequest>
<restriction/>
<entityIdList>
<entityId type="EventbusEvent" isPattern="true">
<id>dk.cavi.eventbus.*</id>
</entityId>
</entityIdList>
</queryContextRequest>
```

It seems that the ```<restriction/>``` should not be present if no restrictions are applied?

**Comment by yalp** [comment]
Hi @dkgof,

Yes, this was a mistake...

Thanks !

**Comment by marcc-orange** [comment]
Hi @dkgof,

Yes, this was a mistake...

Thanks !
