### ISSUE TITLE
Move NGSI library to a dedicated repo

### ISSUE THREAD

**Issue by marcc-orange** [Orange-OpenSource/fiware-cepheus#43]
The `cepheus-ngsi` library currently is under the GPLv2 licence which is very restrictive for library reuse. We will move the `cepheus-ngsi` library to its own git repo and modify the licensing to use Apache Licence v2.

**Comment by marcc-orange** [comment]
We just created a dedicated repository for the NGSI v1 API library : [Orange-OpenSource/fiware-ngsi-api](https://github.com/Orange-OpenSource/fiware-ngsi-api).

We also started working on a new library to support the upcoming NGSI v2 API : [Orange-OpenSource/fiware-ngsi2-api](https://github.com/Orange-OpenSource/fiware-ngsi2-api)

**Comment by LM450N** [comment]
Thank you ! :tada:

**Comment by marcc-orange** [comment]
Migration is now effective for the cepheus project on master: 10fefc907b81ad427f242d851ac50426df9bda47
