### ISSUE TITLE
Notification not triggered if subscription contains subset of updated attributes

### ISSUE THREAD

**Issue by psartini** [Orange-OpenSource/fiware-cepheus#45]
There is a Subscription on:

> entityId = device.12345
> attributes = "temperature"

Let's send an updateContext with 2 attributes:

> temperature = 15.0
> pressure = 200

*Result:* No notification is triggered. 

If we send an updateContext with only one temperature attribute, the notification gets fired:

> temperature = 15.0

*Result:* Notification is triggered.  Subscription works.

If we do the same thing with Orion Broker, the behaviour is different.
Is this a bug in cepheus?

**Comment by marcc-orange** [comment]
Thanks for the bug report.

Please note that Cepheus-Broker has a really basic support for subscription/notification (mentioned [here](http://fiware-cepheus.readthedocs.org/en/latest/broker/index.html#limitations)).
Additionally, when a subscription matches a least one the context element of an updatecontext, the whole set of context elements are sent in the payload notification, there is no filtering as in the Orion Context Broker.

**Comment by psartini** [comment]
That was fast, thank's for fixing!  :+1:
