### ISSUE TITLE
Adding persistance to Cepheus

### ISSUE THREAD

**Issue by sabrine2020** [Orange-OpenSource/fiware-cepheus#50]
Hello,

We are interested in adding persistance to Cepheus gateway.
We are working on a project that needs this feature and we are ready to contribute! 

Thanks and best regards,
Sabrine FATNASSI 
Easy Global Market

**Comment by marcc-orange** [comment]
After you last comment on SO, I added a new issue #49 to discuss your feature. I added some ideas. Could you comment on this issue ? Thanks.
