### ISSUE TITLE
Use Docker parameters for Cepheus configuration

### ISSUE THREAD

**Issue by chazemar** [Orange-OpenSource/fiware-cepheus#55]
Use docker parameters to parameterize cepheus (remote.url for example) instead of call configuration API.

**Comment by marcc-orange** [comment]
Docker can pass any parameters to`orangeopensource/fiware-cepheus-broker` and `orangeopensource/fiware-cepheus-cep` images, as we intentionally defined an `ENTRYPOINT` but left the `CMD` empty.

This cannot be done with the `orangeopensource/fiware-cepheus` image as both CEP and Broker daemons are running inside the same container using `supervisord` (which is convenient for quickly testing both services with the default settings but not a Docker recommended practice for deploying services).

Example:

    docker run -d --name cepheus-broker -p 8081:8081 orangeopensource/fiware-cepheus-broker --remote.url="http://server:port"

For more info see the Docker [run command documentation](https://docs.docker.com/engine/reference/run/#/cmd-default-command-or-options).

**Comment by chazemar** [comment]
Thx.
