### ISSUE TITLE
change remote.url in docker container

### ISSUE THREAD

**Issue by khanbaba** [Orange-OpenSource/fiware-cepheus#62]
Hi,
I used the below code to run my docker cepheus image:
docker run -d --name cepheus1 -p 8080:8080 -p 8081:8081 orangeopensource/fiware-cepheus
And my orion context broker is on 1026 port
How can i change remote broker default value to forward updated to orion ?

thanks

**Comment by marcc-orange** [comment]
It is not clear to me if you want to use cepheus-cep or cepheus-broker, or both.

When using the fiware-cepheus docker image, both cepheus-cep and cepheus-broker are run using supervisord (this is more intended for demo purpose). You can modify the `docker/supervisord.conf` file to change the remote broker for Cepheus-Broker.

I would however recommend that you use the two Docker images dedicated to each component, for more info check `fiware-cep/docker` and `fiware-broker/docker`.

To configure the cepheus-broker, using the `--remote-url=http://orion-server:port/path` options (see Configuration section of the [manual](http://fiware-cepheus.readthedocs.io/en/latest/admin/broker/index.html)).

For the cepheus-cep, things are a bit diffrent as the remote broker can be configured for each statement (see `Brokers` and `Providers` fields in [configuration](http://fiware-cepheus.readthedocs.io/en/latest/cep/configuration/index.html)).

**Comment by khanbaba** [comment]
Thanks Marc,
According to Docs the remote.url default value is: localhost:8082.
So I changed my Orion Context Broker to port 8082, But also the updateContext on cepheus-broker is not forwarding to Orion.
Do you have any idea ?? Does Cepheus-Broker send any updateContext to remote broker (orion) ?

**Comment by khanbaba** [comment]
Thanks Marc.

**Comment by khanbaba** [comment]
as the docs tell, the remote.url default value is: localhost:8082.
so i changed my Orion to listen on port 8082, but still there is no message from cepheus broker to orion.
what is wrong ? I think that any /v1/updateContext messages to cepheus broker must be forwarded to Orion automatically, is this true ?

**Comment by marcc-orange** [comment]
Yes, fiware-broker will forward all updateContext messages to the `remote.url` which is `http://localhost:8082` by default. Check the logs for any error.

**Comment by khanbaba** [comment]
Yes there is the following error message on cepheus-broker:

WARN 1 --- [pool-2-thread-1] c.o.c.broker.controller.NgsiController: UpdateContext failed for http://localhost:8082: Connection refused
java.net.ConnectionException: Connection refused

**Comment by marcc-orange** [comment]
So it does not seem like the problem is comming from cepheus... it looks like Orion is not responding on port `localhost:8082`.

**Comment by khanbaba** [comment]
Thank you very much,
i think the correct path must be something like http://localhost:8082/v1 no http://localhost:8082

**Comment by DavidCorral94** [comment]
Hello, did anyone get an solution for this? I tried to create a link between my Cepheus container and my Orion container but I still get connection refused. What could be happening?
