### ISSUE TITLE
Cepheus does not send subscribeContext request on changing ServiceName and ServicePath

### ISSUE THREAD

**Issue by Adeeb-khan** [Orange-OpenSource/fiware-cepheus#69]
On sending config.json file with provider field as below:
"providers":[
        { 
          "url":"http://orion:1026",
          "serviceName":"tenant",
          "servicePath":"/test"
        }
      ]
Cepheus send a subscribe context request to the this provider.

Now if you change the service name or service path,Cepheus will not send subscribe context request. Cepheus sends subscribe context request only when the url in provider will change.

**Comment by ansh1221** [comment]
I hereby request you to kindly merge the pull request,if the changes are correct.

**Comment by iamarnavgarg** [comment]
I hereby request you to kindly merge the pull request,if the changes are correct.

**Comment by marcc-orange** [comment]
@iamarnavgarg I added a comment on the pull request.
https://github.com/Orange-OpenSource/fiware-cepheus/pull/71#issuecomment-395333963
